language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'

before_script:
  - wget http://www.sketchapp.com/download/sketch.zip
  - unzip sketch.zip
  - ./Sketch.app/Contents/Resources/sketchtool/install.sh
  - npm install

script:
  - ./node_modules/gulp/bin/gulp.js sketch
